# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ship', '0002_auto_20161024_2119'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('user', 'type')]),
        ),
    ]
